---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    driver_config:
      customize:
        memory: 768

suites:
  - name: default
    run_list:
      - recipe[sftp::default]
    attributes:
